version: '3.9'
services:
  metabase_full_app_embedding_demo:
    build: metabase/.
    container_name: metabase_full_app_embedding_demo
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      - "MB_SITE_URL=http://localhost:3000"
      # - "MB_SESSION_COOKIE_SAMESITE=None"
      - "MB_EMBEDDING_APP_ORIGIN=*"
      - "MB_ENABLE_EMBEDDING=true"
      - "MB_PREMIUM_EMBEDDING_TOKEN=blablabla"
      - "MB_JWT_ENABLED=true"
      - "MB_JWT_IDENTITY_PROVIDER_URI=http://localhost:8080/api/auth/metabase"
      - "MB_JWT_SHARED_SECRET=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
      - "MB_EMAIL_SMTP_HOST=maildev-sub"
      - "MB_EMAIL_SMTP_PASSWORD=password"
      - "MB_EMAIL_SMTP_PORT=25"
      - "MB_EMAIL_SMTP_SECURITY=none"
      - "MB_EMAIL_SMTP_USERNAME=admin"
      - "MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=false"
    networks: 
      - metanet1
  setup_full_app_embedding_demo:
    image: bash:5.1.16
    container_name: setup_full_app_embedding_demo
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      - metabase_full_app_embedding_demo
    command: sh /tmp/metabase-setup.sh metabase:3000
  node_full_app_embedding_demo:
    build: webapp/.
    container_name: webapp_full_app_embedding_demo
    hostname: webapp
    ports:
      - 8080:8080
    networks:
      - metanet1
    environment:
      - METABASE_URL=http://localhost:3000
      - PORT=8080
  maildev-sso:
    image: maildev/maildev:1.1.0
    container_name: maildev-sso
    hostname: maildev-sso
    ports:
    - "3002:80"
    networks:
    - metanet1
    cpus: 1
    mem_limit: 128m
networks: 
  metanet1:
    driver: bridge
